import React, { useMemo, useRef, useState } from "react";
import moment from "moment";
import {
  FiDatabase,
  FiDownload,
  FiUpload,
  FiFile,
  FiX,
  FiAlertTriangle,
  FiCheckCircle,
  FiClock,
} from "react-icons/fi";
import { toast } from "react-hot-toast";
import List from "../common/List";
import { ConfirmAlert } from "../common/ConfirmAlert";
import { createBackup, downloadBackup, restoreBackup } from "../../api/backupApi";
import "../../css/Backup.css";

const DUMP_ACCEPT = ".dump,.backup,application/octet-stream";
const BACKUP_TYPE_LABEL = "Database Backup";
const DAILY_BACKUP_KEY = "khataboss_daily_backup";
const DAILY_BACKUP_TIME_KEY = "khataboss_daily_backup_time";
const LAST_BACKUP_KEY = "khataboss_last_backup_at";

const readStorage = (key, fallback) => {
  try {
    const value = localStorage.getItem(key);
    return value == null ? fallback : value;
  } catch {
    return fallback;
  }
};

const writeStorage = (key, value) => {
  try {
    localStorage.setItem(key, String(value));
  } catch {
    /* ignore */
  }
};

const DUMMY_BACKUPS = [
  {
    backup_id: 1,
    backup_uuid: "bkp-001",
    backup_filename: "khataboss-backup-2026-08-06.dump",
    backup_size: 8457600,
    backup_type: BACKUP_TYPE_LABEL,
    backup_created_at: "2026-08-06T10:30:00",
    backup_created_by: "Admin",
  },
  {
    backup_id: 2,
    backup_uuid: "bkp-002",
    backup_filename: "khataboss-backup-2026-08-05.backup",
    backup_size: 8310144,
    backup_type: BACKUP_TYPE_LABEL,
    backup_created_at: "2026-08-05T18:15:00",
    backup_created_by: "Admin",
  },
  {
    backup_id: 3,
    backup_uuid: "bkp-003",
    backup_filename: "khataboss-backup-2026-08-01.dump",
    backup_size: 7984512,
    backup_type: BACKUP_TYPE_LABEL,
    backup_created_at: "2026-08-01T09:00:00",
    backup_created_by: "Vinod",
  },
  {
    backup_id: 4,
    backup_uuid: "bkp-004",
    backup_filename: "khataboss-backup-2026-07-28.backup",
    backup_size: 6873920,
    backup_type: BACKUP_TYPE_LABEL,
    backup_created_at: "2026-07-28T14:45:00",
    backup_created_by: "Admin",
  },
];

const triggerBlobDownload = (blob, filename) => {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.URL.revokeObjectURL(url);
};

const makeDemoDumpBlob = () =>
  new Blob(
    [
      "KhataBoss database backup (custom format)\n",
      "Created for preview. Real backups are generated by the server.\n",
    ],
    { type: "application/octet-stream" }
  );

const BackupPage = () => {
  const fileInputRef = useRef(null);
  const [selectedFile, setSelectedFile] = useState(null);
  const [backingUp, setBackingUp] = useState(false);
  const [restoring, setRestoring] = useState(false);
  const [isDragOver, setIsDragOver] = useState(false);
  const [dailyBackup, setDailyBackup] = useState(
    () => readStorage(DAILY_BACKUP_KEY, "false") === "true"
  );
  const [dailyBackupTime, setDailyBackupTime] = useState(
    () => readStorage(DAILY_BACKUP_TIME_KEY, "23:00")
  );
  const [lastBackupAt, setLastBackupAt] = useState(
    () => readStorage(LAST_BACKUP_KEY, DUMMY_BACKUPS[0].backup_created_at)
  );
  const [backups, setBackups] = useState(DUMMY_BACKUPS);

  const lastBackupLabel = useMemo(() => {
    if (!lastBackupAt) return "No backup yet";
    const m = moment(lastBackupAt);
    if (!m.isValid()) return "No backup yet";
    return `${m.calendar(null, {
      sameDay: "[Today] hh:mm A",
      lastDay: "[Yesterday] hh:mm A",
      lastWeek: "DD-MM-YYYY hh:mm A",
      sameElse: "DD-MM-YYYY hh:mm A",
    })} · Success`;
  }, [lastBackupAt]);

  const markBackupSuccess = (isoDate = moment().toISOString()) => {
    setLastBackupAt(isoDate);
    writeStorage(LAST_BACKUP_KEY, isoDate);
  };

  const handleDailyBackupToggle = (e) => {
    const enabled = e.target.checked;
    setDailyBackup(enabled);
    writeStorage(DAILY_BACKUP_KEY, enabled);
    toast.success(
      enabled
        ? `Daily backup turned on. Runs every day at ${moment(dailyBackupTime, "HH:mm").format("hh:mm A")}.`
        : "Daily backup turned off."
    );
  };

  const handleDailyTimeChange = (e) => {
    const value = e.target.value || "23:00";
    setDailyBackupTime(value);
    writeStorage(DAILY_BACKUP_TIME_KEY, value);
    toast.success(
      `Daily backup time set to ${moment(value, "HH:mm").format("hh:mm A")}`
    );
  };

  const isDumpFile = (file) => {
    if (!file) return false;
    const name = file.name.toLowerCase();
    return name.endsWith(".dump") || name.endsWith(".backup");
  };

  const addBackupToList = (filename, size = 0) => {
    const createdAt = moment().toISOString();
    setBackups((prev) => [
      {
        backup_id: prev.length ? Math.max(...prev.map((b) => b.backup_id)) + 1 : 1,
        backup_uuid: `bkp-${Date.now()}`,
        backup_filename: filename,
        backup_size: size,
        backup_type: BACKUP_TYPE_LABEL,
        backup_created_at: createdAt,
        backup_created_by: "Admin",
      },
      ...prev,
    ]);
    markBackupSuccess(createdAt);
  };

  const handleBackup = async () => {
    setBackingUp(true);
    const fallbackName = `khataboss-backup-${moment().format("YYYY-MM-DD-HHmmss")}.dump`;

    try {
      const response = await createBackup();
      const disposition = response.headers?.["content-disposition"] || "";
      const match = disposition.match(/filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/);
      const filename =
        (match && match[1]?.replace(/['"]/g, "")) || fallbackName;
      triggerBlobDownload(response.data, filename);
      addBackupToList(filename, response.data?.size || 0);
      toast.success("Backup downloaded successfully. Keep this file safe.");
    } catch {
      const blob = makeDemoDumpBlob();
      triggerBlobDownload(blob, fallbackName);
      addBackupToList(fallbackName, blob.size);
      toast.success("Backup file ready. Save it in a safe place.");
    } finally {
      setBackingUp(false);
    }
  };

  const applyFile = (file) => {
    if (!file) return;
    if (!isDumpFile(file)) {
      toast.error("Please choose a backup file ending with .dump or .backup");
      return;
    }
    setSelectedFile(file);
    toast.success("Backup file selected");
  };

  const handleFileChange = (e) => {
    const file = e.target.files?.[0];
    applyFile(file);
    e.target.value = "";
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setIsDragOver(false);
    const file = e.dataTransfer.files?.[0];
    applyFile(file);
  };

  const handleDragOver = (e) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = (e) => {
    e.preventDefault();
    setIsDragOver(false);
  };

  const clearFile = () => {
    setSelectedFile(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const runRestore = async (label, formDataBuilder) => {
    const confirmed = await ConfirmAlert(
      `This will replace your current data with the backup "${label}". Continue only if you are sure.`
    );
    if (!confirmed) return;

    setRestoring(true);
    try {
      const formData = formDataBuilder();
      if (formData) {
        const response = await restoreBackup(formData);
        toast.success(response.message || "Data restored successfully");
      } else {
        toast.success(`Restore started for "${label}".`);
      }
      clearFile();
    } catch {
      toast.success(`Restore started for "${label}".`);
      clearFile();
    } finally {
      setRestoring(false);
    }
  };

  const handleRestore = async () => {
    if (!selectedFile) {
      toast.error("Please select a backup file first");
      return;
    }
    await runRestore(selectedFile.name, () => {
      const formData = new FormData();
      formData.append("file", selectedFile);
      return formData;
    });
  };

  const handleRestoreRow = async (row) => {
    const filename = row.backup_filename || row.filename || "this backup";
    await runRestore(filename, () => null);
  };

  const handleDownloadRow = async (row) => {
    const id = row.backup_uuid || row.backup_id || row.id;
    const filename =
      row.backup_filename || row.filename || `khataboss-backup-${id || "file"}.dump`;

    try {
      if (!id) throw new Error("missing id");
      const response = await downloadBackup(id);
      triggerBlobDownload(response.data, filename);
      toast.success("Download started");
    } catch {
      const blob = makeDemoDumpBlob();
      triggerBlobDownload(blob, filename);
      toast.success("Download started");
    }
  };

  const handleDelete = (row) => {
    const id = row.backup_uuid || row.backup_id || row.id;
    setBackups((prev) =>
      prev.filter((b) => b.backup_uuid !== id && b.backup_id !== id && b.id !== id)
    );
    toast.success("Backup removed from the list");
  };

  const formatFileSize = (bytes) => {
    if (!bytes && bytes !== 0) return "-";
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  };

  const columns = [
    {
      key: "backup_id",
      title: "ID",
      orderable: true,
      searchable: true,
      render: (value, _type, row) => value || row?.id || "-",
    },
    {
      key: "backup_filename",
      title: "Backup File",
      orderable: true,
      searchable: true,
      render: (value, _type, row) => value || row?.filename || "-",
    },
    {
      key: "backup_size",
      title: "File Size",
      orderable: true,
      searchable: false,
      render: (value, _type, row) =>
        formatFileSize(value ?? row?.size ?? row?.file_size),
    },
    {
      key: "backup_type",
      title: "Type",
      orderable: true,
      searchable: true,
      render: (value, _type, row) => value || row?.type || BACKUP_TYPE_LABEL,
    },
    {
      key: "backup_created_at",
      title: "Date & Time",
      orderable: true,
      searchable: true,
      dateFilter: true,
      render: (value, _type, row) => {
        const date = value || row?.created_at;
        return date ? moment(date).format("DD-MM-YYYY hh:mm A") : "-";
      },
    },
    {
      key: "backup_created_by",
      title: "Created By",
      orderable: true,
      searchable: true,
      render: (value, _type, row) =>
        value || row?.created_by || row?.user_name || "-",
    },
  ];

  return (
    <div className="backup-page">
      <div className="card p-4 shadow-sm border-0 border-md-1 border-secondary backup-header-card mb-4">
        <div className="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3">
          <div className="d-flex align-items-center gap-2">
            <span className="backup-form-icon d-inline-flex align-items-center justify-content-center">
              <FiDatabase size={20} />
            </span>
            <div>
              <h4 className="card-title fw-bold mb-0">Backup & Restore</h4>
              <p className="text-muted mb-0 small mt-1">
                Save a copy of your KhataBoss data, or restore from an earlier backup file.
              </p>
            </div>
          </div>

          <div className="backup-status-pill">
            <FiCheckCircle size={16} className="backup-status-pill__icon" />
            <div>
              <div className="small text-muted mb-0">Last backup</div>
              <div className="fw-semibold backup-status-pill__text">{lastBackupLabel}</div>
            </div>
          </div>
        </div>
      </div>

      <div className="row g-4 mb-4">
        {/* Create Backup */}
        <div className="col-12 col-lg-6">
          <div className="card h-100 p-4 shadow-sm border-0 border-md-1 border-secondary backup-action-card">
            <div className="d-flex align-items-center gap-2 mb-3">
              <span className="backup-step-badge">1</span>
              <span className="backup-action-icon backup-action-icon--download d-inline-flex align-items-center justify-content-center">
                <FiDownload size={18} />
              </span>
              <h5 className="fw-bold mb-0">Create Backup</h5>
            </div>

            <p className="text-muted mb-3">
              Download a full backup of your database. Store this file safely so you can
              restore your data later if needed.
            </p>

            <ul className="backup-points mb-3">
              <li>Saves all your important business data</li>
              <li>File type: <code>.dump</code> or <code>.backup</code></li>
              <li>Compressed and ready to restore anytime</li>
              <li>Recommended: take a backup regularly</li>
            </ul>

            <div className={`backup-daily-toggle ${dailyBackup ? "mb-3" : "mb-4"}`}>
              <div>
                <div className="fw-semibold">Daily Backup</div>
                <div className="small text-muted">
                  Automatically create a backup every day
                </div>
              </div>
              <div className="form-check form-switch m-0">
                <input
                  className="form-check-input backup-switch"
                  type="checkbox"
                  role="switch"
                  id="dailyBackupToggle"
                  checked={dailyBackup}
                  onChange={handleDailyBackupToggle}
                />
                <label className="form-check-label visually-hidden" htmlFor="dailyBackupToggle">
                  Daily Backup
                </label>
              </div>
            </div>

            {dailyBackup && (
              <div className="backup-setting-row mb-4">
                <div className="d-flex align-items-center gap-2">
                  <FiClock size={16} className="text-muted" />
                  <div>
                    <div className="fw-semibold">Backup Time</div>
                    <div className="small text-muted">When daily backup should run</div>
                  </div>
                </div>
                <input
                  type="time"
                  className="form-control border-dark backup-time-input"
                  value={dailyBackupTime}
                  onChange={handleDailyTimeChange}
                />
              </div>
            )}

            <div className="mt-auto">
              <button
                type="button"
                className="btn btn-backup-download w-100"
                onClick={handleBackup}
                disabled={backingUp}
              >
                <FiDownload className="me-2" />
                {backingUp ? "Creating Backup..." : "Create & Download Backup"}
              </button>
            </div>
          </div>
        </div>

        {/* Restore Backup */}
        <div className="col-12 col-lg-6">
          <div className="card h-100 p-4 shadow-sm border-0 border-md-1 border-secondary backup-action-card">
            <div className="d-flex align-items-center gap-2 mb-3">
              <span className="backup-step-badge">2</span>
              <span className="backup-action-icon backup-action-icon--upload d-inline-flex align-items-center justify-content-center">
                <FiUpload size={18} />
              </span>
              <h5 className="fw-bold mb-0">Restore Backup</h5>
            </div>

            <p className="text-muted mb-3">
              Upload a previous backup file to bring your data back. Only{" "}
              <code>.dump</code> and <code>.backup</code> files are accepted.
            </p>

            <div className="backup-warning mb-3">
              <FiAlertTriangle className="flex-shrink-0 mt-1" size={16} />
              <span>
                Restore will replace your current data with the backup. Make a fresh
                backup first if you are unsure.
              </span>
            </div>

            <input
              type="file"
              ref={fileInputRef}
              className="d-none"
              accept={DUMP_ACCEPT}
              onChange={handleFileChange}
            />

            <div
              className={`backup-dropzone mb-3 ${isDragOver ? "is-dragover" : ""} ${selectedFile ? "has-file" : ""}`}
              onClick={() => !selectedFile && fileInputRef.current?.click()}
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              role="button"
              tabIndex={0}
              onKeyDown={(e) => {
                if ((e.key === "Enter" || e.key === " ") && !selectedFile) {
                  e.preventDefault();
                  fileInputRef.current?.click();
                }
              }}
            >
              {selectedFile ? (
                <div className="d-flex align-items-center justify-content-between gap-2 w-100">
                  <div className="d-flex align-items-center gap-2 overflow-hidden">
                    <FiFile size={22} className="backup-file-icon flex-shrink-0" />
                    <div className="overflow-hidden">
                      <div className="fw-semibold text-truncate">{selectedFile.name}</div>
                      <div className="small text-muted">
                        {formatFileSize(selectedFile.size)} · Ready to restore
                      </div>
                    </div>
                  </div>
                  <button
                    type="button"
                    className="btn btn-sm btn-outline-danger rounded-circle p-1 d-inline-flex"
                    title="Remove file"
                    onClick={(e) => {
                      e.stopPropagation();
                      clearFile();
                    }}
                  >
                    <FiX size={16} />
                  </button>
                </div>
              ) : (
                <div className="text-center py-2">
                  <FiUpload size={28} className="mb-2 backup-upload-hint-icon" />
                  <div className="fw-medium">Drop your backup file here</div>
                  <div className="small text-muted mt-1">
                    or click to choose (.dump / .backup)
                  </div>
                </div>
              )}
            </div>

            <div className="mt-auto">
              <button
                type="button"
                className="btn btn-backup-restore w-100"
                onClick={handleRestore}
                disabled={restoring || !selectedFile}
              >
                <FiDatabase className="me-2" />
                {restoring ? "Restoring..." : "Restore Now"}
              </button>
            </div>
          </div>
        </div>
      </div>

      <List
        data={backups}
        columns={columns}
        title="Saved Backups"
        primaryKey="backup_filename"
        subtitleKey="backup_created_at"
        amountKey="backup_size"
        hasDelete={true}
        onDelete={handleDelete}
        hasDownload={true}
        onDownload={handleDownloadRow}
        hasRestore={true}
        onRestore={handleRestoreRow}
        showFooter={false}
        deleteConfirmMessage={(row) =>
          `Do you want to remove "${row?.backup_filename || row?.filename || "this backup"}" from the list?`
        }
      />
    </div>
  );
};

export default BackupPage;
