import moment from 'moment';

export const buildFormTemplateTestData = (firmName = 'Sample Firm') => ({
  firm_name: firmName,
  firm_shop_name: `${firmName} — Main Branch`,
  firm_reg_no: 'ML-2024-00125',
  firm_address: '12, MG Road, Pune, Maharashtra - 411001',
  firm_phone_no: '9876543210',
  firm_pan_no: 'ABCDE1234F',
  firm_gstin_no: '27ABCDE1234F1Z5',
  customer_name: 'Rajesh Kumar Sharma',
  customer_address: 'Flat 302, Sai Residency, Kothrud, Pune - 411038',
  customer_mobile: '9123456789',
  customer_aadhaar: 'XXXX-XXXX-4521',
  customer_pan: 'FGHIJ5678K',
  customer_photo: 'On file',
  owner_name_address: 'Same as pawner',
  loan_no: 'GL-2026-00482',
  loan_date: moment().subtract(45, 'days').format('DD-MM-YYYY'),
  loan_amount: '1,50,000.00',
  interest_rate: '18% p.a. (Simple)',
  interest_type: 'Simple Monthly',
  loan_period: '12 Months',
  due_date: moment().add(320, 'days').format('DD-MM-YYYY'),
  loan_status: 'ACTIVE — Pledge in custody',
  item_description: 'Gold necklace with pendant (1 piece)',
  item_metal: 'Gold',
  item_gross_wt: '45.250 g',
  item_net_wt: '42.100 g',
  item_purity: '22K (916)',
  item_pieces: '1',
  item_value: '2,85,000.00',
  total_interest: '11,250.00',
  total_deposit: '15,000.00',
  outstanding: '1,36,250.00',
  last_transaction_date: moment().subtract(5, 'days').format('DD-MM-YYYY'),
  date_of_redemption: '—',
  redeeming_person: '—',
  release_remarks: 'Pledge active — not yet redeemed',
  payment_date: moment().subtract(5, 'days').format('DD-MM-YYYY'),
  principal_paid: '5,000.00',
  interest_paid: '2,250.00',
  balance_principal: '1,45,000.00',
  balance_interest: '9,000.00',
  initials: 'PB',
  txn_date: moment().subtract(5, 'days').format('DD-MM-YYYY'),
  txn_type: 'Deposit',
  txn_amount: '5,000.00',
  txn_narration: 'Partial interest + principal payment',
  today_date: moment().format('DD-MM-YYYY'),
  loan_amount_raw: 150000,
  outstanding_raw: 136250,
});

export const getFormFieldValue = (fieldId, data) =>
  data?.[fieldId] ?? '—';

export const getFieldTestValue = getFormFieldValue;

export const TRANSACTION_TEST_ROWS = [
  {
    payment_date: moment().subtract(45, 'days').format('DD-MM-YYYY'),
    principal_paid: '—',
    interest_paid: '—',
    balance_principal: '1,50,000.00',
    balance_interest: '—',
    initials: 'PB',
    txn_date: moment().subtract(45, 'days').format('DD-MM-YYYY'),
    txn_type: 'Opening',
    txn_amount: '1,50,000.00',
    txn_narration: 'Loan disbursed — principal',
  },
  {
    payment_date: moment().subtract(30, 'days').format('DD-MM-YYYY'),
    principal_paid: '5,000.00',
    interest_paid: '5,000.00',
    balance_principal: '1,45,000.00',
    balance_interest: '4,500.00',
    initials: 'PB',
    txn_date: moment().subtract(30, 'days').format('DD-MM-YYYY'),
    txn_type: 'Deposit',
    txn_amount: '10,000.00',
    txn_narration: 'Interest + partial principal',
  },
  {
    payment_date: moment().subtract(5, 'days').format('DD-MM-YYYY'),
    principal_paid: '5,000.00',
    interest_paid: '2,250.00',
    balance_principal: '1,40,000.00',
    balance_interest: '2,250.00',
    initials: 'PB',
    txn_date: moment().subtract(5, 'days').format('DD-MM-YYYY'),
    txn_type: 'Deposit',
    txn_amount: '7,250.00',
    txn_narration: 'Partial payment',
  },
];
